"""create teams, tasks, projects tables and relationships

Revision ID: d0f9534f2808
Revises: ffdc0a98111c
Create Date: 2021-09-22 11:39:48.536867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f9534f2808'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(length=55), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=55), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
