"""removed projId from teams table

Revision ID: f9291c18c8af
Revises: 45e3259705da
Create Date: 2021-09-22 15:49:06.182358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9291c18c8af'
down_revision = '45e3259705da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=255), nullable=False),
    sa.Column('teamMemberId', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=75), nullable=False),
    sa.ForeignKeyConstraint(['teamMemberId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projOwner', sa.Integer(), nullable=False),
    sa.Column('projName', sa.String(length=255), nullable=False),
    sa.Column('projDesc', sa.Text(), nullable=False),
    sa.Column('projStatus', sa.String(length=50), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['projOwner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignedTo', sa.Integer(), nullable=False),
    sa.Column('projId', sa.Integer(), nullable=False),
    sa.Column('taskBody', sa.Text(), nullable=False),
    sa.Column('taskStatus', sa.String(length=75), nullable=True),
    sa.Column('taskPriority', sa.String(length=75), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignedTo'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('projects')
    op.drop_table('teams')
    # ### end Alembic commands ###
