"""fixing relations proj team

Revision ID: fc6e4521d27d
Revises: f9291c18c8af
Create Date: 2021-09-22 18:22:00.413778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6e4521d27d'
down_revision = 'f9291c18c8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_teamId_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'teamId')
    op.add_column('teams', sa.Column('projId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'projects', ['projId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'projId')
    op.add_column('projects', sa.Column('teamId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_teamId_fkey', 'projects', 'teams', ['teamId'], ['id'])
    # ### end Alembic commands ###
