"""removed created and updated times for teams table

Revision ID: 45e3259705da
Revises: d0f9534f2808
Create Date: 2021-09-22 12:56:03.558884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e3259705da'
down_revision = 'd0f9534f2808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePic', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePic')
    # ### end Alembic commands ###
